from django.conf.urls import url
from .views import (
    nueva_factura, search_productos,
    vivero_factura, save_facturaReal,
    SelFacturas, AllFacturas, SearchFac, pdfFactura,
    selViveroPro, getProductos, ViveroRem, remionesAll,
    nuevaRemision, remisionCliente, remisionProductos,
    saveRemision, copiaFactura, ventasPOS, productosPos,
    viveroPos, savePos, clientePos, clienteFactura, detalleRemision, allPedidos,
    nuevoPedido, clientePedido, productoPedido, guardarPedi, copiaRemision, detallePedido, abonosPedido,
    copiaAbono, copiaPedido, jsonPedidos, pagoFactura, cancelFactura
)

urlpatterns = [
    url(r'^seleccionar/$', vivero_factura, name='viverofactura'),
    url(r'^viveroproductos/$', selViveroPro, name='viveroproductos'),
    url(r'^pedidos/$', allPedidos, name='pedidos'),
    url(r'^pedidos/json/$', jsonPedidos, name='json'),
    url(r'^pedidos/nuevo/$', nuevoPedido, name='nuevopedido'),
    url(r'^pedidos/nuevo/cliente/$', clientePedido, name='cliente'),
    url(r'^pedidos/nuevo/producto/$', productoPedido, name='producto'),
    url(r'^pedidos/nuevo/guardar/$', guardarPedi, name='guardar'),
    url(r'^pedidos/detalle/(?P<id>\w+)/$', detallePedido, name='detallepedido'),
    url(r'^pedidos/detalle/(?P<id>\w+)/copia/$', copiaAbono, name='copiaabono'),
    url(r'^pedidos/detalle/(?P<id>\w+)/copia_pedido/$',
        copiaPedido, name='copiapedido'),
    url(r'^pedidos/(?P<id>\w+)/abono/$',
        abonosPedido.as_view(), name='abonopedido'),


    url(r'^remisiones/$',
        remionesAll, name='remisiones'),
    url(r'^remisiones/nueva/$',
        nuevaRemision.as_view(), name='crearremision'),
    url(r'^remisiones/detalle/(?P<remision_id>\w+)/$',
        detalleRemision, name='detalleremision'),
    url(r'^remisiones/detalle/(?P<remision_id>\w+)/copia/$',
        copiaRemision, name='copiaremision'),
    url(r'^remisiones/nueva/cliente/$',
        remisionCliente, name='remisioncliente'),
    url(r'^remisiones/nueva/producto/$',
        remisionProductos, name='remisionproducto'),
    url(r'^remisiones/nueva/guardar/$',
        saveRemision, name='saveRemision'),
    url(r'^viveroproductos/(?P<pro>\w+)/productos/$',
        getProductos, name='getproductos'),
    url(r'^selvivero/$', SelFacturas, name='selfacturas'),
    url(r'^facturas/$',
        AllFacturas, name='allfacturas'),
    url(r'^facturas/cancel/$',
        cancelFactura, name='cancelfactura'),
    url(r'^facturas/pago/$',
        pagoFactura, name='pagofactura'),
    url(r'^facturas/nueva/$',
        nueva_factura, name='nuevafactura'),
    url(r'^facturas/nueva/productos/$',
        search_productos, name='searchpro'),
    url(r'^facturas/nueva/cliente/$',
        clienteFactura, name='searchCli'),
    url(r'^facturas/nueva/savefactura/$',
        save_facturaReal, name='saveInvoicereal'),
    url(r'^facturas/detallefac/(?P<fac>\w+)/copia/$',
        copiaFactura, name='copiafactura'),
    url(r'^facturas/detallefac/(?P<fac>\w+)/$',
        SearchFac, name='detallefactura'),
    url(r'^facturas/detallefac/(?P<fac>\w+)/generar/$',
        SearchFac, name='generarcopiafactura'),
    url(r'^pos/$', ventasPOS, name='pos'),
    url(r'^pos/save/$', savePos, name='savepos'),
    url(r'^pos/vivero/$', viveroPos, name='vivero'),
    url(r'^pos/productopos/$',
        productosPos, name='productopos'),
    url(r'^pos/clientepos/$',
        clientePos, name='clientepos'),

    # url(r'^facturas/(?P<pro>\w+)/detallefac/(?P<fac>\w+)/pdf$',
    #     pdfFactura.as_view(), name='pdfFactura'),

]
