# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-18 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='abonoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('valorabono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_cate', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria Producto',
                'verbose_name_plural': 'Categoria Productos ',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_cc', models.CharField(blank=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Detalle_FacturaDoble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('val_unitario', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('val_neto', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle Factura Doble',
                'verbose_name_plural': 'Detalle Facturas Dobles',
            },
        ),
        migrations.CreateModel(
            name='Detalle_FacturaReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('val_unitario', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('val_neto', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle Factura Real',
                'verbose_name_plural': 'Detalle Facturas Reales',
            },
        ),
        migrations.CreateModel(
            name='detalleRemison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('val_unitario', models.IntegerField(null=True)),
                ('iva', models.IntegerField(null=True)),
                ('val_neto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detalleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de Usuario',
                'verbose_name_plural': 'Detalles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='estadoPedido',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDoble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='FacturaReal',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.EstadoFactura')),
            ],
            options={
                'verbose_name': 'Factura Real',
                'verbose_name_plural': 'Facturas Reales',
            },
        ),
        migrations.CreateModel(
            name='Numeracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=100)),
                ('fecha', models.DateField(null=True)),
                ('num_ini', models.IntegerField()),
                ('num_fin', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Numeracion',
                'verbose_name_plural': 'Numeraciones',
            },
        ),
        migrations.CreateModel(
            name='PagosFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('valorabono', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.FacturaReal')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
                ('estadopedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.estadoPedido')),
            ],
        ),
        migrations.CreateModel(
            name='pedidoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('val_unitario', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('val_neto', models.IntegerField(null=True)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Presentacion Producto',
                'verbose_name_plural': 'Presentacion Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('barras', models.CharField(max_length=100, null=True)),
                ('precio_venta', models.IntegerField(blank=True, null=True, verbose_name='precio')),
                ('iva_porce', models.IntegerField(null=True, verbose_name='iva')),
                ('precio_compra', models.IntegerField(null=True)),
                ('tran_porce', models.IntegerField(null=True, verbose_name='Trasporte %')),
                ('mayor_porce', models.IntegerField(null=True, verbose_name='Utilidad x mayor %')),
                ('general_porce', models.IntegerField(null=True, verbose_name='ganancia %')),
                ('precioxmayor', models.IntegerField(blank=True, null=True, verbose_name='precio al por mayor')),
                ('valor_real_compra', models.IntegerField(blank=True, null=True, verbose_name='valor compra real')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Categoria', verbose_name='Categoria')),
                ('id_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Presentacion', verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.EstadoFactura')),
            ],
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vivero',
                'verbose_name_plural': 'Viveros',
            },
        ),
        migrations.AddField(
            model_name='remision',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vivero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='numeracion',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='facturareal',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='facturadoble',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='detalleuser',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='detalleremison',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
        migrations.AddField(
            model_name='detalleremison',
            name='remision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Remision'),
        ),
        migrations.AddField(
            model_name='detalle_facturareal',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.FacturaReal'),
        ),
        migrations.AddField(
            model_name='detalle_facturareal',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
        migrations.AddField(
            model_name='detalle_facturadoble',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.FacturaDoble'),
        ),
        migrations.AddField(
            model_name='detalle_facturadoble',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
        migrations.AddField(
            model_name='abonopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Pedido'),
        ),
    ]
