# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_cate', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categoria Productos ',
                'verbose_name': 'Categoria Producto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_cc', models.CharField(blank=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Detalle_FacturaDoble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('val_unitario', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('val_neto', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Detalle Facturas Dobles',
                'verbose_name': 'Detalle Factura Doble',
            },
        ),
        migrations.CreateModel(
            name='Detalle_FacturaReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('val_unitario', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('val_neto', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Detalle Facturas Reales',
                'verbose_name': 'Detalle Factura Real',
            },
        ),
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDoble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'verbose_name': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='FacturaReal',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.EstadoFactura')),
            ],
            options={
                'verbose_name_plural': 'Facturas Reales',
                'verbose_name': 'Factura Real',
            },
        ),
        migrations.CreateModel(
            name='Numeracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=100)),
                ('fecha', models.DateField(null=True)),
                ('num_ini', models.IntegerField()),
                ('num_fin', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Numeraciones',
                'verbose_name': 'Numeracion',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Presentacion Productos',
                'verbose_name': 'Presentacion Producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_venta', models.IntegerField(null=True, verbose_name='precio')),
                ('iva_porce', models.IntegerField(null=True, verbose_name='iva')),
                ('precio_compra', models.IntegerField(blank=True, null=True)),
                ('tran_porce', models.IntegerField(null=True, verbose_name='Trasporte %')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Categoria', verbose_name='Categoria')),
                ('id_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Presentacion', verbose_name='Presentación')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Viveros',
                'verbose_name': 'Vivero',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='vivero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='numeracion',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='facturareal',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='facturadoble',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero'),
        ),
        migrations.AddField(
            model_name='detalle_facturareal',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.FacturaReal'),
        ),
        migrations.AddField(
            model_name='detalle_facturareal',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
        migrations.AddField(
            model_name='detalle_facturadoble',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.FacturaDoble'),
        ),
        migrations.AddField(
            model_name='detalle_facturadoble',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
    ]
