# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mayor_porce',
            field=models.IntegerField(null=True, verbose_name='Utilidad x mayor %'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioxmayor',
            field=models.IntegerField(null=True, verbose_name='precio al por mayor'),
        ),
    ]
