# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20170209_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valor_real_compra',
            field=models.IntegerField(blank=True, null=True, verbose_name='valor compra real'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='mayor_porce',
            field=models.IntegerField(blank=True, null=True, verbose_name='Utilidad x mayor %'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioxmayor',
            field=models.IntegerField(blank=True, null=True, verbose_name='precio al por mayor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tran_porce',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trasporte %'),
        ),
    ]
