# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20170209_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleRemison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
                ('vivero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Vivero')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='mayor_porce',
            field=models.IntegerField(null=True, verbose_name='Utilidad x mayor %'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tran_porce',
            field=models.IntegerField(null=True, verbose_name='Trasporte %'),
        ),
        migrations.AddField(
            model_name='detalleremison',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
        migrations.AddField(
            model_name='detalleremison',
            name='remision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Remision'),
        ),
    ]
