# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20170404_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremison',
            name='iva',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detalleremison',
            name='val_neto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detalleremison',
            name='val_unitario',
            field=models.IntegerField(null=True),
        ),
    ]
