# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20170421_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.EstadoFactura'),
        ),
    ]
