# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20170824_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoPedido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
    ]
