# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_estadopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopedido',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
