# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_remove_detallepedido_descuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estado',
            new_name='estado_id',
        ),
    ]
