# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_auto_20170827_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estado_id',
            new_name='estado_id_id',
        ),
    ]
