# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_auto_20170906_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='pedid',
            new_name='pedido',
        ),
    ]
