# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_auto_20170906_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detallePedido',
            new_name='pedidoDetalle',
        ),
    ]
