# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_auto_20170906_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pedidoDetalle',
            new_name='detallePedido',
        ),
    ]
