# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_auto_20170906_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('valorabono', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.FacturaReal')),
            ],
        ),
    ]
