# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_pagosfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='barras',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
