# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_auto_20180211_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='general_porce',
            field=models.IntegerField(null=True, verbose_name='ganancia %'),
        ),
    ]
